title: Isaac Revette # your name (or website title) here
logo: "/images/pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MS in Business Analytics Candidate at the Simon Business School - University of Rochester Graduating in May 2020.
  <br><br>
  Extensive work in in leveraging modern data science techniques to derive business insights from data.
  <br><br>
  <a href="/pdf/Isaac_Revette_Resume.pdf">View My Resume</a>
  <br><br>
  <a href="https://www.linkedin.com/in/isaacrevette/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
